### ISSUE TITLE
Quais eventos?

### ISSUE THREAD

**Issue by paulodealmeida** [bahiacoders/agenda#1]
Vi que na lista de eventos só tem eventos de São Paulo, não deveriam ser só da Bahia? ou o que tem lá são eventos que vieram junto com o fork?

**Comment by mvfsilva** [comment]
São os eventos que vieram junto com o FORK, ainda não tive tempo para fazer as alterações, mas ao invés de usar sistema de PR vamos usar o firebase correto?

**Comment by paulodealmeida** [comment]
Isso mesmo, só estava analisando o código pra ver como era.
