### ISSUE TITLE
Json vs Jekyll

### ISSUE THREAD

**Issue by gjuniioor** [bahiacoders/agenda#1]
Então, bora criar a agenda para centralizar os eventos de tech na Bahia!!

A dúvida: Fazer com um simples json mostrado na página inicial ou um projeto com Jekyll?

Com Jekyll, podemos usar o tema [Evento](http://evento.davidboyne.co.uk/) que já é um bom caminho andado. 

Com Json seria o caso de experimentar novas coisas.

Fazemos votação ou pensamos melhor nos prós e contras?

**Comment by paulodealmeida** [comment]
Acho que podia ser jekyll mesmo, a não ser que tenha um app mobile, mas acho que não vai ser o caso

**Comment by jjaderg** [comment]
Boa discurssão. Cara se for usar json, vai ser legal pra por exemplo, consumir num app mobile, algo que eu tava pensando em fazer tbm. Porem o Jekyll ja ta pronto praticamente. Aí a gente tem que votar mesmo, creio que o Json seja uma boa, entao voto nele!

**Comment by gjuniioor** [comment]
Se tem a possibilidade de um App com esses dados, acho Json bacana então. Jekyll seria questão para ser mais rápido. Como pressa não se dá muito bem com coisa bem feita, voto no Json então! :D 

Poderia, se for o caso, adotar o layout do tema, mas alimentando com esse json.

**Comment by paulodealmeida** [comment]
Podia ser assim oh,

ser em json e lá no site ele ser consumido em cima de algo parecido com o template do evento, o que acham?

Eu acho o json muito melhor e mais flexivel para outras implementações.

**Comment by jjaderg** [comment]
Acho Json o melhor mesmo. Voces tem disponibilidade para fazer isso?

**Comment by paulodealmeida** [comment]
Senhores, my bad, fiz o push direto no gh-pages sem fazer PR, por favor olhem lá.

**Comment by gjuniioor** [comment]
@paulodealmeida, tranquilo :)

Então será que podemos fazer assim: Jekyll para questão de reutilização e modularização de código mas com os eventos estruturados em um json?

**Comment by paulodealmeida** [comment]
Sei não, pois o jekyll usa markdown para renderizar, ai não sei como fazer

**Comment by gjuniioor** [comment]
Jekyll usa markdown também, mas a base é html. Assim, se o conteúdo tiver em markdown, ele faz o parser e transforma para html.

Falei de usar ele para no caso de ter mais páginas, por exemplo, para documentação "Sobre" o projeto, "Como Contribuir" com o projeto, não precisar repetir as coisas ... Mas a página index, que seria onde teria listado todos os eventos, continua lendo o json.

**Comment by mvfsilva** [comment]
Acho melhor que seja em Json!
Agora esses eventos serão minerados ou cadastrados pela comunidade?

**Comment by paulodealmeida** [comment]
Inicialmente acho que deve ser cadastrados, depois podemos evoluir para minerar.

**Comment by gjuniioor** [comment]
Concordo, cadastrado por quem faz o evento é mais bacana :D

**Comment by mvfsilva** [comment]
Então vamos de firebase?

**Comment by paulodealmeida** [comment]
Nunca usei, mas pode ser uma boa pedida.

**Comment by gjuniioor** [comment]
Não conheço, mas se acham uma boa, que seja :D

**Comment by mvfsilva** [comment]
O [firebase](https://www.firebase.com/) é bem fácil e lindo :hamster:

**Comment by paulodealmeida** [comment]
A parte gratuita do firebase consegue nos dar suporte?

**Comment by mvfsilva** [comment]
Com certeza, fazemos nossa agenda apagar os eventos automaticamente após a sua determinada data, acho que ele nos fornece 10GB free, se for isso com certeza ele dá;

**Comment by paulodealmeida** [comment]
hands on
